package com.katandao.server.game;

public enum GameActionType {
    PLACE_INITIAL_SETTLEMENT,
    PLACE_INITIAL_ROAD,
    ROLL_DICE,
    BUILD_ROAD,
    BUILD_SETTLEMENT,
    BUILD_CITY,
    BUY_DEVELOPMENT_CARD,
    PLAY_KNIGHT,
    PLAY_ROAD_BUILDING,
    PLAY_YEAR_OF_PLENTY,
    PLAY_MONOPOLY,
    TRADE_WITH_BANK,
    PROPOSE_PLAYER_TRADE,
    RESPOND_PLAYER_TRADE,
    MOVE_ROBBER,
    STEAL_RESOURCE,
    END_TURN
}
